version: "3.8"

services:
  authenticatie:
    image: poc-authenticatie
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
