version: "3.8"

services:
  editor:
    image: nginx:alpine
    ports:
      - "3003:3003"
    configs:
      - source: index_html
        target: /usr/share/nginx/html/index.html
      - source: level_json
        target: /usr/share/nginx/html/level.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  index_html:
    file: ./src/index.html
  level_json:
    file: ./src/level.json
