version: "3.8"

services:
  authenticatie:
    image: node:18-alpine
    ports:
      - "3005:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
